sudo: false

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-9.0.0.0
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2

install:
  - wget https://github.com/summerwind/h2spec/releases/download/v1.5.0/h2spec_linux_amd64.zip
  - unzip h2spec_linux_amd64.zip

script:
  - cd example
  - ruby server.rb --secure > /dev/null &
  - sleep 1
  - cd
  - ./h2spec_linux_amd64/h2spec -o 1 -p 8080 -t -k
